# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parsCovFuns_cpp <- function(type) {
    .Call(`_SpatioTemporal_parsCovFuns_cpp`, type)
}

#' Returns a list of possible covariance function names
#'
#' Available covariance functions (\code{d} is the distance
#' between points):
#' \describe{
#'   \item{\code{exp,exponential}}{Exponential covariance:
#'     \deqn{\sigma^2 \exp(-d/\rho)}{sill * exp( -d/range )} }
#'   \item{\code{exp2,exponential2,gaussian}}{Gaussian/double
#'     exponential covariance:
#'     \deqn{\sigma^2 \exp(-(d/\rho)^2)}{sill * exp( -(d/range)^2 )} }
#'   \item{\code{cubic}}{Cubic covariance: 
#'     \deqn{\sigma^2 (1 - 7 (d/\rho)^2 + 8.75 (d/\rho)^3 -
#'           3.5 (d/\rho)^5 + 0.75 (d/\rho)^7)}{sill*(1 -
#'           7*(d/range)^2 + 8.75*(d/range)^3 - 3.5*(d/range)^5 +
#'           0.75*(d/range)^7)}
#'     if \eqn{d<\rho}{d<range}.}
#'   \item{\code{spherical}}{Spherical covariance: 
#'     \deqn{\sigma ^2(1 - 1.5(d/\rho) + 0.5 (d/\rho)^3)}{sill * (1 -
#'           1.5*(d/range) + 0.5*(d/range)^3)}
#'     if \eqn{d<\rho}{d<range}.}
#'   \item{\code{matern}}{Matern covariance: 
#'     \deqn{\frac{\sigma^2}{\Gamma(\nu) 2^{\nu-1}}
#'           \left(\frac{d\sqrt{8\nu}}{\rho}\right)^\nu
#'           K_\nu\left(\frac{d\sqrt{8\nu}}{\rho}\right)}{sill /
#'           (gamma(shape)*2^(shape-1)) *
#'           (d*sqrt(8*shape)/range)^shape *
#'           besselK( (d*sqrt(8*shape)/range), shape ) } }
#'   \item{\code{cauchy}}{Cauchy covariance: 
#'     \deqn{ \frac{\sigma^2}{(1 + (d/\rho)^2)^{\nu}}}{sill *
#'           (1 + (d/range)^2) ^ -shape} }
#'   \item{\code{iid}}{IID covariance, i.e. zero matrix 
#'     since nugget is added afterwards. \deqn{0}{0}}
#' }
#' 
#' @title Available covariance functions
#' @return Character vector with valid covariance function names.
#' 
#' @examples
#'   namesCovFuns()
#' 
#' @author Johan Lindstrom
#' @family covariance functions
#' @import Rcpp
#' @export
namesCovFuns <- function() {
    .Call(`_SpatioTemporal_namesCovFuns`)
}

evalCovFuns_cpp <- function(type, pars, d, diff) {
    .Call(`_SpatioTemporal_evalCovFuns_cpp`, type, pars, d, diff)
}

dist_Cpp <- function(coord) {
    .Call(`_SpatioTemporal_dist_Cpp`, coord)
}

crossDist_Cpp <- function(coord1, coord2) {
    .Call(`_SpatioTemporal_crossDist_Cpp`, coord1, coord2)
}

expandF_cpp <- function(F, loc_ind, n_loc) {
    .Call(`_SpatioTemporal_expandF_cpp`, F, loc_ind, n_loc)
}

loglikeST_cpp <- function(x_in, x_fixed, type, Y_in, F, M_FX, type_B, type_nu, nugget_matrix, n_cov_pars, dist_B, dist_nu, blocks, ind) {
    .Call(`_SpatioTemporal_loglikeST_cpp`, x_in, x_fixed, type, Y_in, F, M_FX, type_B, type_nu, nugget_matrix, n_cov_pars, dist_B, dist_nu, blocks, ind)
}

loglikeSTnaive_cpp <- function(x_in, x_fixed, type, Y_in, F, M_FX, type_B, type_nu, nugget_matrix, n_cov_pars, dist_B, dist_nu, blocks, ind) {
    .Call(`_SpatioTemporal_loglikeSTnaive_cpp`, x_in, x_fixed, type, Y_in, F, M_FX, type_B, type_nu, nugget_matrix, n_cov_pars, dist_B, dist_nu, blocks, ind)
}

loglikeST_test_cpp <- function(x_in, x_fixed, type, Y_in, F, M_FX, type_B, type_nu, nugget_matrix, n_cov_pars, dist_B, dist_nu, blocks, ind) {
    .Call(`_SpatioTemporal_loglikeST_test_cpp`, x_in, x_fixed, type, Y_in, F, M_FX, type_B, type_nu, nugget_matrix, n_cov_pars, dist_B, dist_nu, blocks, ind)
}

makeSigmaB_cpp <- function(par, dist, type, nugget, symmetry, ind2_to_1) {
    .Call(`_SpatioTemporal_makeSigmaB_cpp`, par, dist, type, nugget, symmetry, ind2_to_1)
}

makeSigmaNu_cpp <- function(par, dist, type, nugget, random_effect, symmetry, blocks1, blocks2, ind1, ind2, ind2_to_1) {
    .Call(`_SpatioTemporal_makeSigmaNu_cpp`, par, dist, type, nugget, random_effect, symmetry, blocks1, blocks2, ind1, ind2, ind2_to_1)
}

